export enum ConfigEnum {
  NODE_ENV = 'NODE_ENV',
  DB_TYPE = 'DB_TYPE',
  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',
  JWT_SECRET = 'JWT_SECRET',

  COS_SECRET_ID = 'COS_SECRET_ID',
  COS_SECRET_KEY = 'COS_SECRET_KEY',
  COS_BUCKET = 'COS_BUCKET',
  COS_REGION = 'COS_REGION',

  EMAIL_HOST = 'EMAIL_HOST',
  EMAIL_PORT = 'EMAIL_PORT',
  EMAIL_AUTH_USER = 'EMAIL_AUTH_USER',
  EMAIL_AUTH_PASS = 'EMAIL_AUTH_PASS',
  EMAIL_FROM = 'EMAIL_FROM',
}
